name: deploy-dev

on:
  
  pull_request:

  workflow_dispatch:
    inputs:
      stack_name:
        type: string
        default: test
        description: Stack to deploy to
        required: true

jobs:
  
  build-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    outputs:
      tag: ${{ steps.build.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_MINION_PAT }}
      - name: Docker Login
        run: echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build
        id: build
        run: DOCKER_PUSH=true ./build.sh

  deploy-dev:
    needs: build-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
        working-directory: pulumi
      - uses: pulumi/actions@35f51396579b3b55f0741396cff6904ec35d3f09 # TODO: update to v3 after next release
        with:
          command: up
          stack-name: ${{ github.event.inputs.stack_name || github.head_ref }}
          upsert: true
          work-dir: pulumi
          comment-on-pr: true
          github-token: ${{ secrets.CI_MINION_PAT }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          TAG: ${{ needs.build-dev.outputs.tag }}
